spring:
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
  application:
    name: cake-platform

  datasource:
    url: jdbc:mysql://${EC2END}:3306/${DATABASE}?serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${USERNAME}
    password: ${PASSWORD}

  jpa:
    hibernate:
      ddl-auto: none
      dialect: org.hibernate.dialect.MySQLDialect
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        highlight_sql: false

    cache:
      type: redis
server:
  port: 8000
jwt:
  secret: ${JWT_SECRET_KEY}

logging:
  config: classpath:logback-spring-${spring.profiles.active}.xml
kakao:
  redirect-uri-signin-owners-kakao: http://cakemate.org:8000/api/owners/kakao/signin
  redirect-uri-signin-customers-kakao: http://cakemate.org:8000/api/customers/kakao/signin
  client-id: ${KAKAO_CLIENT_ID}
  client-secret: ${KAKAO_CLIENT_SECRET}
  kauth-host: https://kauth.kakao.com
  kapi-host: https://kapi.kakao.com